name: Create component changes list
runs:
  using: composite
  steps:
    - name: Check out release branch from GitHub
      uses: actions/checkout@v4.1.2
      with:
        repository: esphome/esphome
        ref: release
        fetch-depth: 500
        path: esphome
    - name: Find changed components
      shell: bash
      working-directory: esphome
      run: ../component-changes/get-changes.sh > output/changed_components.json
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: component-changes
        path: output/changed_components.json
